-- Doctors table
CREATE TABLE IF NOT EXISTS public.dokter (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email TEXT NOT NULL,
  spesialis TEXT NOT NULL,
  lokasi TEXT,
  lokasi_rumah_sakit TEXT,
  pengalaman TEXT,
  harga_konsultasi DECIMAL(10,2),
  pendidikan JSONB, -- Array of education entries
  rating DECIMAL(3,2),
  jumlah_ulasan INTEGER DEFAULT 0,
  bahasa JSONB, -- Array of languages
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT dokter_pkey PRIMARY KEY (id),
  CONSTRAINT dokter_email_fkey FOREIGN KEY (email) REFERENCES public.user(email) ON DELETE CASCADE,
  CONSTRAINT dokter_email_unique UNIQUE (email)
);

-- Admins table
CREATE TABLE IF NOT EXISTS public.admin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email TEXT NOT NULL,
  department TEXT,
  access_level TEXT,
  last_login TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT admin_pkey PRIMARY KEY (id),
  CONSTRAINT admin_email_fkey FOREIGN KEY (email) REFERENCES public.user(email) ON DELETE CASCADE,
  CONSTRAINT admin_email_unique UNIQUE (email)
);
